# Amber
# Theme create by: Me 
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "rose-pine"

# ========= Border =========
file_panel_border = "#664e45"
sidebar_border = "#af828b"
footer_border = "#af828b"

# ========= Border Active =========
file_panel_border_active = "#f3c0ad"
sidebar_border_active = "#e7aabe"
footer_border_active = "#e7aabe"
modal_border_active = "#e7aabe"

# ========= Background (bg) =========
full_screen_bg = "#151016"
file_panel_bg = "#151016"
sidebar_bg = "#151016"
footer_bg = "#151016"
modal_bg = "#151016"

# ========= Foreground (fg) =========
file_panel_fg = "#e5c5b9"
full_screen_fg = "#b7ada5"
sidebar_fg = "#b7ada5"
footer_fg = "#b7ada5"
modal_fg = "#b7ada5"

# ========= Special Color =========
cursor = "#b7ada5"
correct = "#95b4ab"
error = "#7a515a"
hint = "#49504f"
cancel = "#d5b5a9"
# Gradient color can only have two color!
gradient_color = ["#46222b", "#e0b19f"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#b7ada5"
file_panel_top_path = "#b7ada5"
file_panel_item_selected_fg = "#af828b"
file_panel_item_selected_bg = "#151016"

# ========= Sidebar Special Items =========
sidebar_title = "#f3c0ad"
sidebar_item_selected_fg = "#af828b"
sidebar_item_selected_bg = "#151016"
sidebar_divider = "#49504f"

# ========= Modal Special Items =========
modal_cancel_fg = "#eee3db"
modal_cancel_bg = "#7a515a"

modal_confirm_fg = "#eee3db"
modal_confirm_bg = "#95b4ab"

# ========= Help Menu =========
help_menu_hotkey = "#cfa0aa"
help_menu_title = "#e5c4b9"
