local shade = require("base46.colors").change_hex_lightness
local mix = require("base46.colors").mix

local M = {}
local base16 = {
	base00 = "#151016",
	base01 = "#1f1a1f",
	base02 = "#2b2525",
	base03 = "#453838",
	base04 = "#725f5f",
	base05 = "#cab8b0",
	base06 = "#9c797d",
	base07 = "#a6ab9f",
	base08 = "#c3aaa1",
	base09 = "#a9a4bf",
	base0A = "#c4959c",
	base0B = "#bfb7a6",
	base0C = "#c6908c",
	base0D = "#abbaad",
	base0E = "#c8bcaa",
	base0F = "#aa8ea2",
}

-- UI
local base30 = {
	white = shade(base16.base07, 10),
	black = base16.base00,
	darker_black = shade(base16.base00, -5),
	black2 = base16.base01,
	one_bg = shade(base16.base02, -5),
	one_bg2 = base16.base02,
	one_bg3 = shade(base16.base02, 5),
	grey = shade(base16.base01, 20),
	grey_fg = shade(base16.base01, 25),
	grey_fg2 = shade(base16.base01, 30),
	light_grey = base16.base04,
	red = base16.base0C,
	baby_pink = shade(base16.base0A, 5),
	pink = base16.base0A,
	line = shade(base16.base06, -20),
	green = base16.base0D,
	vibrant_green = shade(base16.base0D, 10),
	nord_blue = base16.base09,
	blue = shade(base16.base09, 5),
	seablue = shade(base16.base09, 10),
	yellow = base16.base0B,
	sun = base16.base0E,
	purple = base16.base0F,
	dark_purple = shade(base16.base0F, -10),
	teal = mix(base16.base0D, base16.base09, 10),
	orange = mix(base16.base08, base16.base0A, 10),
	cyan = mix(base16.base09, base16.base0D, 10),
	statusline_bg = base16.base03,
	lightbg = base16.base07,
	pmenu_bg = base16.base03,
	folder_bg = base16.base03,
}

local polish_hl = {
	defaults = {
		Comment = { fg = base16.base04, italic = true, bold = true },
		Added = { fg = base30.yellow },
		Removed = { fg = base30.baby_pink },
		Changed = { fg = base30.purple },

		WinBar = { bg = shade(base16.base03, -18) },
		WinBarNC = { bg = shade(base16.base03, -18) },
		WinSeparator = { fg = base30.line },
		Pmenu = { bg = base30.pmenu_bg, fg = base16.base04 },
		PmenuSbar = { bg = base30.pmenu_bg },
		PmenuSel = { bg = shade(base16.base06, -30), fg = shade(base30.orange, 20), bold = true },
		PmenuThumb = { bg = base30.grey },
		FloatBorder = { fg = base30.red },
		FloatTitle = { fg = base30.red, bg = base16.base00 },
		NormalFloat = { bg = base16.base00 },
		Title = { fg = base16.base0D, sp = "none" },
		WildMenu = { fg = base16.base08, bg = base16.base0A },

		QuickFixLine = { bg = base16.base01, sp = "none" },
		Question = { fg = base16.base0D },
		Search = { fg = base16.base01, bg = base16.base08 },
		Substitute = { fg = base16.base01, bg = base16.base0A, sp = "none" },
		IncSearch = {
			bg = base30.orange,
			fg = shade(base16.base07, -50),
			bold = true,
			italic = true,
		},
		MatchWord = { link = "IncSearch" },
		MatchParen = { link = "MatchWord" },

		Normal = { fg = base16.base05, bg = base16.base00 },
		Italic = { italic = true },
		Bold = { bold = true },
		UnderLined = { underline = true },
		Conceal = { bg = "NONE" },
		NonText = { fg = base16.base0B },
		DevIconDefault = { fg = base30.red },
		Directory = { fg = base16.base0D },

		ModeMsg = { fg = base16.base0B },
		MoreMsg = { fg = base16.base0B },
		Visual = {
			bg = shade(base30.nord_blue, -30),
			fg = base30.orange,
			italic = true,
			bold = true,
		},
		VisualNOS = { fg = base16.base09 },
		Macro = { fg = base16.base08 },

		Cursor = { fg = base16.base00, bg = base16.base05 },
		CursorColumn = { bg = base16.base01, sp = "none" },
		CursorLine = { bg = mix(shade(base30.white, -40), base16.base00, 75) },
		CursorLineNr = { fg = base30.white },
		SignColumn = { fg = base16.base03, sp = "NONE" },
		ColorColumn = { bg = base30.black2 },
		LineNr = { fg = base16.base04 },
		FoldColumn = { bg = "none" },
		Folded = { fg = base30.light_grey, bg = base30.black2 },
		CurSearch = { fg = base30.black2, bg = base30.sun, bold = true },

		Error = { fg = base30.red, bg = base30.statusline_bg },
		ErrorMsg = { fg = base30.red, bg = base30.statusline_bg },
		Exception = { fg = base16.base08 },
		healthSuccess = { bg = base30.green, fg = base30.black },
		Debug = { fg = base16.base08 },
		WarningMsg = { fg = base16.base08 },
		SpecialKey = { fg = base16.base03 },
		TooLong = { fg = base16.base08 },
		NvimInternalError = { fg = base30.red },

		SpellBad = { undercurl = true, sp = base16.base08 },
		SpellLocal = { undercurl = true, sp = base16.base0C },
		SpellCap = { undercurl = true, sp = base16.base0D },
		SpellRare = { undercurl = true, sp = base16.base0E },

		-- Lazy
		LazyH1 = {
			bg = shade(base16.base06, -40),
			fg = base30.green,
			bold = true,
		},
		LazyButton = {
			bg = shade(base16.base06, -40),
			fg = shade(base30.purple, 10),
		},
		LazyButtonActive = {
			bg = shade(base16.base06, -40),
			fg = base30.green,
			bold = true,
		},
		LazyH2 = { fg = base30.white, bold = true, italic = true, underline = false },
		LazyReasonPlugin = { fg = base30.red },
		LazyValue = { fg = base30.teal },
		LazyDir = { fg = base16.base05 },
		LazyUrl = { fg = base16.base05 },
		LazyCommit = { fg = base30.green },
		LazyNoCond = { fg = base30.red },
		LazySpecial = { fg = base16.base0B },
		LazyReasonFt = { fg = base30.purple },
		LazyOperator = { fg = base30.white },
		LazyReasonKeys = { fg = base30.teal },
		LazyTaskOutput = { fg = base30.white },
		LazyCommitIssue = { fg = base30.pink },
		LazyReasonEvent = { fg = base30.yellow },
		LazyReasonStart = { fg = base30.white },
		LazyReasonRuntime = { fg = base30.nord_blue },
		LazyReasonCmd = { fg = base30.sun },
		LazyReasonSource = { fg = base30.cyan },
		LazyReasonImport = { fg = base30.white },
		LazyProgressDone = { fg = base30.green },
	},
	statusline = {
		St_LspMsg = { fg = base16.base06 },
		St_Lsp = { fg = base16.base06 },
	},
	neogit = {
		NeogitCommitViewHeader = {
			bg = shade(base30.purple, -40),
			fg = base16.base08,
		},
		NeogitDiffContext = {
			bg = shade(base16.base03, -18),
			fg = base30.light_grey,
		},
		NeogitDiffContextHighlight = {
			bg = shade(base16.base03, -15),
			fg = base30.light_grey,
		},
		NeogitDiffContextCursor = {
			bg = shade(base16.base03, -15),
			fg = base16.base08,
		},
		NeogitHunkHeader = {
			fg = shade(base16.base08, -20),
			bg = shade(base16.base04, -25),
		},
		NeogitHunkHeaderHighlight = {
			fg = shade(base16.base04, -30),
			bg = shade(base16.base08, -15),
		},
		NeogitHunkHeaderCursor = {
			fg = shade(base16.base04, -30),
			bg = shade(base16.base08, -15),
		},
		NeogitDiffAdd = {
			fg = shade(base30.green, -20),
			bg = shade(base30.green, -65),
		},
		NeogitDiffAddHighlight = {
			fg = shade(base30.green, -8),
			bg = shade(base30.green, -55),
		},
		NeogitDiffAddCursor = {
			fg = mix(base30.green, "#FFFFFF", 50),
			bg = shade(base30.green, -55),
		},
		NeogitDiffDelete = {
			fg = shade(base30.red, -10),
			bg = shade(base30.red, -60),
		},
		NeogitDiffDeleteHighlight = {
			fg = shade(base30.red, -3),
			bg = shade(base30.red, -50),
		},
		NeogitDiffDeleteCursor = {
			fg = mix(base30.red, "#FFFFFF", 30),
			bg = shade(base30.red, -50),
		},
	},
	nvimtree = {
		NvimTreeEmptyFolderName = { fg = base30.folder_bg },
		NvimTreeEndOfBuffer = { fg = base30.darker_black },
		NvimTreeFolderIcon = { fg = base30.folder_bg },
		NvimTreeFolderName = { fg = base30.folder_bg },
		NvimTreeFolderArrowOpen = { fg = base30.folder_bg },
		NvimTreeFolderArrowClosed = { fg = base30.grey_fg },
		NvimTreeGitDirty = { fg = base30.red },
		NvimTreeOpenedFolderName = { fg = base30.folder_bg },
		NvimTreeGitIgnored = { fg = base30.light_grey },
		NvimTreeWinSeparator = { fg = base30.lightbg, bg = base30.menu_bg },
		NvimTreeWindowPicker = { fg = base30.red, bg = base30.black2 },
		NvimTreeCursorLine = { bg = base30.black },
		NvimTreeGitNew = { fg = base30.yellow },
		NvimTreeGitDeleted = { fg = base30.red },
		NvimTreeSpecialFile = { fg = base30.yellow, bold = true },
		NvimTreeRootFolder = { fg = base30.red, bold = true },
	},
	arrow = {
		["@ArrowFileIndex"] = { fg = base30.yellow },
		["@ArrowCurrentFile"] = { fg = base30.yellow },
	},

	barbar = {
		["@BufferVisibleNumber"] = { fg = base30.cyan },
		["@BufferVisibleIcon"] = { fg = base30.cyan },
		["@BufferVisibleSign"] = { fg = base30.cyan },
		["@BufferVisibleSignRight"] = { fg = base30.cyan },
	},

	markview = {
		["@markup.heading.1.markdown"] = { fg = base16.base0F },
		["@markup.heading.2.markdown"] = { fg = shade(base16.base0F, 10) },
		["@markup.heading.3.markdown"] = { fg = base16.base06 },
		["@markup.heading.4.markdown"] = { fg = shade(base16.base06, 10) },
		["@markup.heading.5.markdown"] = { fg = shade(base16.base0E, -20) },
		["@markup.heading.6.markdown"] = { fg = shade(base16.base0E, -10) },
	},
	treesitter = {
		["@variable"] = { fg = base16.base08 },
		["@variable.r"] = { fg = mix(base16.base08, "#DDDDDD", 25) },
		["@variable.member.r"] = { fg = shade(base16.base08, -3) },
		["@variable.builtin"] = { fg = shade(base16.base0F, 10) },
		["@variable.parameter"] = { fg = base16.base08 },
		["@variable.parameter.r"] = { fg = base16.base06 },
		["@variable.member"] = { fg = base16.base08 },
		["@variable.member.key"] = { fg = base16.base08 },

		["@module"] = { fg = base16.base08 },

		["@constant"] = { fg = base16.base06 },
		["@constant.builtin"] = { fg = base16.base06 },
		["@constant.macro"] = { fg = base16.base08 },

		["@string.regex"] = { fg = base16.base0C },
		["@string.escape"] = { fg = base16.base0C },
		["@string.csv"] = { fg = base16.base04 },
		["@character"] = { fg = base16.base08 },
		["@number"] = { fg = base16.base09 },
		-- ["@number.r"] = { fg = base16.base0F },
		["@number.csv"] = { fg = base16.base06 },
		["@number.float"] = { fg = base16.base09 },
		-- ["@number.float.r"] = { fg = base16.base0F },

		["@annotation"] = { fg = base16.base0F },
		["@attribute"] = { fg = base16.base0A },
		["@error"] = { fg = base16.base08 },

		["@keyword.exception"] = { fg = base16.base08 },
		["@keyword"] = { fg = base16.base0E },
		["@keyword.function"] = { fg = base16.base09 },
		["@keyword.function.r"] = { fg = base16.base0F },
		["@keyword.return"] = { fg = base16.base0E },
		["@keyword.operator"] = { fg = base16.base0E },
		["@keyword.import"] = { link = "Include" },
		["@keyword.conditional"] = { fg = base16.base0E },
		["@keyword.conditional.ternary"] = { fg = base16.base0E },
		["@keyword.repeat"] = { fg = base16.base0A },
		["@keyword.storage"] = { fg = base16.base0A },
		["@keyword.directive.define"] = { fg = base16.base0E },
		["@keyword.directive"] = { fg = base16.base0A },

		["@function"] = { fg = base16.base0D },
		["@function.builtin"] = { fg = base16.base0D },
		["@function.macro"] = { fg = base16.base08 },
		["@function.call"] = { fg = base16.base0D },
		["@function.method"] = { fg = base16.base0D },
		["@function.method.call"] = { fg = base16.base0D },
		["@constructor"] = { fg = base16.base0C },
		["@constructor.lua"] = { fg = base16.base0F },

		["@operator"] = { fg = base16.base06 },
		["@operator.r"] = { fg = base16.base06 },
		["@reference"] = { fg = base16.base05 },
		["@punctuation.bracket"] = { fg = base16.base0F },
		["@punctuation.delimiter"] = { fg = base16.base06 },
		["@punctuation.bracket.r"] = { fg = base16.base0F },
		["@punctuation.delimiter.r"] = { fg = base16.base06 },
		["@symbol"] = { fg = base16.base0B },
		["@tag"] = { fg = base16.base0A },
		["@tag.attribute"] = { fg = base16.base08 },
		["@tag.delimiter"] = { fg = base16.base0F },
		["@text"] = { fg = base16.base05 },
		["@text.emphasis"] = { fg = base16.base09 },
		["@text.strike"] = { fg = base16.base0F, strikethrough = true },
		["@type.builtin"] = { fg = base16.base0A },
		["@definition"] = { sp = base16.base04, underline = true },
		["@scope"] = { bold = true },
		["@property"] = { fg = base16.base08 },

		-- markup
		["@markup.heading"] = { fg = base16.base0D },
		["@markup.raw"] = { fg = base16.base09 },
		["@markup.link"] = { fg = base16.base08 },
		["@markup.link.url"] = { fg = base16.base09, underline = true },
		["@markup.link.label"] = { fg = base16.base0C },
		["@markup.list.markdown"] = { fg = base16.base07 },
		["@markup.strong"] = { bold = true },
		["@markup.underline"] = { underline = true },
		["@markup.italic"] = { italic = true },
		["@markup.strikethrough"] = { strikethrough = true },
		["@markup.quote"] = { bg = base30.black2 },
		["@comment"] = { fg = base16.base04 },
		["@comment.todo"] = { fg = base30.grey, bg = base30.white },
		["@comment.warning"] = { fg = base30.black2, bg = base16.base09 },
		["@comment.note"] = { fg = base30.black, bg = base30.blue },
		["@comment.danger"] = { fg = base30.black2, bg = base30.red },
		["@diff.plus"] = { fg = base30.green },
		["@diff.minus"] = { fg = base30.red },
		["@diff.delta"] = { fg = base30.light_grey },
	},
	whichkey = {
		WhichKey = { fg = base16.base06 },
		WhichKeySeparator = { link = "WinSeparator" },
		WhichKeyDesc = { fg = base16.base08 },
		WhichKeyGroup = { fg = base16.base06 },
		WhichKeyValue = { fg = base16.base06 },
	},
	syntax = {
		Boolean = { fg = base16.base09 },
		Character = { fg = base16.base08 },
		Conditional = { fg = base16.base0E },
		Constant = { fg = base16.base08 },
		Define = { fg = base16.base0E, sp = "none" },
		Delimiter = { fg = base16.base0F },
		Float = { fg = base16.base06 },
		Variable = { fg = base16.base05 },
		Function = { fg = base16.base0D },
		Identifier = { fg = base16.base08, sp = "none" },
		Include = { fg = base16.base0D },
		Keyword = { fg = base16.base0E },
		Label = { fg = base16.base0A },
		Number = { fg = base16.base09 },
		Operator = { fg = base16.base06, sp = "none" },
		PreProc = { fg = base16.base0A },
		Repeat = { fg = base16.base0A },
		Special = { fg = base16.base0B },
		SpecialChar = { fg = base16.base0F },
		Statement = { fg = base16.base08 },
		StorageClass = { fg = base16.base0A },
		String = { fg = base16.base05 },
		Structure = { fg = base16.base0E },
		Tag = { fg = base16.base0A },
		Todo = { fg = base16.base0A, bg = base16.base01 },
		Type = { fg = base16.base0A, sp = "none" },
		Typedef = { fg = base16.base0A },
	},
}

M.base_16 = base16
M.base_30 = base30
M.polish_hl = polish_hl
M.type = "dark"

M = require("base46").override_theme(M, "amber")

return M
