# general
background = '#1d1b1d'
border_fg = '#b38098'
text_fg = '#c8a89d'
dimmed_text_fg = '#afafb6'
# input
input_text_fg = '#bf8f94'
result_count_fg = '#bf8f94'
# results
result_name_fg = '#c8a89d'
result_line_number_fg = '#49504f'
result_value_fg = '#afafb6'
selection_bg = '#2b1d2c'
match_fg = '#bf8f94'
# preview
preview_title_fg = '#dcb08d'
# modes
channel_mode_fg = '#8ea592'
remote_control_mode_fg = '#97bf9d'
send_to_channel_mode_fg = '#80a0a4'
