return {
	"folke/snacks.nvim",
	dependencies = { "echasnovski/mini.icons" },
	enabled = vim.env.KITTY_SCROLLBACK_NVIM ~= "true",
	priority = 1000,
	opts = {
		styles = { scratch = { width = 0.6, height = 0.95 } },
		bigfile = {},
		image = {},
		-- input = {},
		scratch = {},
		quickfile = {},
		indent = { chunk = {} },
		statuscolumn = {
			left = { "fold", "git" },
			right = { "mark", "sign" },
			folds = { git_hl = false },
		},
		picker = {
			ui_select = false,
			layout = { preset = "ivy" },
			sources = {
				explorer = {
					cycle = true,
					auto_close = false,
					layout = { preview = "main" },
				},
			},
		},
		dashboard = {
			sections = {
				{ section = "header" },
				{
					gap = 1,
					padding = 1,
					{ icon = " ", key = "d", desc = "Directories", action = ":FzfLua zoxide" },
					{ icon = "󱞋 ", key = "e", desc = "Explore", action = ":Oil" },
					{ icon = "󰱽 ", key = "s", desc = "Search", action = ":FzfLua files" },
					{ icon = "󱎸 ", key = "g", desc = "Grep", action = ":FzfLua live_grep" },
					{ icon = " ", key = "c", desc = "Config", action = ":ChezFzf" },
					{ icon = "󰁯 ", key = "r", desc = "Restore", section = "session" },
					{ icon = "󰊢 ", key = "n", desc = "Neogit", action = ":Neogit" },
					{ icon = "󰒲 ", key = "l", desc = "Lazy", action = ":Lazy" },
					{ icon = "󰩈 ", key = "q", desc = "Quit", action = ":qa" },
				},
				{ section = "startup" },
				{
					pane = 2,
					section = "terminal",
					cmd = "colorscript -e fade",
					height = 7,
					padding = 1,
				},
				{
					pane = 2,
					icon = " ",
					title = "Recent (cwd)",
					cwd = true,
					section = "recent_files",
					indent = 3,
					padding = 1,
					limit = 3,
				},
				{
					pane = 2,
					icon = "󰪶 ",
					title = "Recent (all)",
					section = "recent_files",
					indent = 3,
					padding = 1,
					limit = 3,
				},
				{
					pane = 2,
					icon = " ",
					title = "Projects",
					section = "projects",
					indent = 3,
					padding = 1,
					limit = 3,
				},
			},
		},
	},
}
