return {
	"folke/snacks.nvim",
    dependencies = { "echasnovski/mini.icons" },
	opts = {
		styles = {
			scratch = {
				width = 0.6,
				height = 0.95,
				bo = { buftype = "", buflisted = false, bufhidden = "hide", swapfile = false },
				minimal = false,
				noautocmd = false,
				zindex = 20,
				wo = { winhighlight = "NormalFloat:Normal" },
				border = "rounded",
				title_pos = "center",
				footer_pos = "center",
			},
		},
		statuscolumn = {
			enabled = true,
			right = {},
			left = { "mark", "sign", "fold" },
			folds = { open = true, git_hl = false },
		},
		image = { enabled = true },
		input = {
			enabled = true,
			win = {
				style = "input",
				title_pos = "left",
				relative = "cursor",
				row = -3,
				col = 0,
				width = 30,
			},
		},
		indent = { enabled = true, chunk = { enabled = true } },
		scratch = {},
		picker = {
			sources = {
				explorer = {
					layout = {
						cycle = true,
                        auto_close = true,
						layout = {
							preview = "main",
							box = "horizontal",
							position = "float",
							height = 0.99,
							width = 0,
							border = "none",
							{
								box = "vertical",
								width = 40,
								min_width = 40,
								{ win = "input", height = 1, title = "{title} {live} {flags}", border = "single" },
								{ win = "list" },
							},
							{ win = "preview", width = 0, border = "left" },
						},
					},
				},
			},
			ui_select = false,
			layout = { preset = "ivy" },
			layouts = {
				vertical = {
					layout = {
						backdrop = false,
						width = 0.4,
						min_width = 80,
						height = 0.8,
						min_height = 30,
						box = "vertical",
						border = "none",
						title = "Images",
						title_pos = "center",
						{
							win = "preview",
							height = 0.8,
							border = { " ", "─", " ", " ", " ", "─", " ", " " },
							-- border = "single",
						},
						{ win = "input", height = 1, border = "none" },
						{ win = "list", border = { " ", "─", " ", " ", " ", "─", " ", " " } },
					},
				},
			},
		},
		dim = {},
		dashboard = {
			sections = {
				{ section = "header" },
				{
					gap = 1,
					padding = 1,
					{ icon = " ", key = "e", desc = "Explore", action = ":Oil" },
					{ icon = "󰱽 ", key = "s", desc = "Search", action = ":FzfLua files" },
					{ icon = "󱎸 ", key = "g", desc = "Grep", action = ":FzfLua live_grep" },
					{ icon = " ", key = "c", desc = "Config", action = ":ChezFzf" },
					{ icon = "󰁯 ", key = "r", desc = "Restore", section = "session" },
					{ icon = "󰊢 ", key = "n", desc = "Neogit", action = ":Neogit" },
					{ icon = "󰒲 ", key = "l", desc = "Lazy", action = ":Lazy" },
					{ icon = "󰩈 ", key = "q", desc = "Quit", action = ":qa" },
				},
				{ section = "startup" },
				{
					pane = 2,
					section = "terminal",
					cmd = "colorscript -e 24",
					height = 7,
					padding = 1,
				},
				{
					pane = 2,
					icon = " ",
					title = "Recent (cwd)",
					cwd = true,
					section = "recent_files",
					indent = 2,
					padding = 1,
					limit = 4,
				},
				{
					pane = 2,
					icon = "󰪶 ",
					title = "Recent (all)",
					section = "recent_files",
					indent = 2,
					padding = 1,
					limit = 4,
				},
				{
					pane = 2,
					icon = "󰊢 ",
					title = "Git Status",
					section = "terminal",
					enabled = function()
						return Snacks.git.get_root() ~= nil
					end,
					cmd = "git status --short --branch --renames",
					height = 5,
					padding = 1,
					ttl = 5 * 60,
					indent = 3,
				},
			},
		},
	},
}
