-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "nightlamp-tempered-V2"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@ibl.indent.char.1", { fg = "#5d545e", nocombine = true })
hi(0, "@ibl.scope.char.1", { bg = "#1f1f21", ctermfg = 11, fg = "#5d545e", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#403741", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#5d545e", nocombine = true })
hi(0, "@keyword.return", { fg = "#e6b8e3" })
hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
hi(0, "@lsp.mod.deprecated", { fg = "#e6b8e3" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "Function" })
hi(0, "@lsp.type.interface", { link = "Structure" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.method", { link = "Function" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "Type" })
hi(0, "@lsp.type.typeParameter", { link = "Typedef" })
hi(0, "@lsp.type.variable", { fg = "#d3c6af" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar", italic = true })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@symbol", { fg = "#9db6d0" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Comment" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@variable", { fg = "#d3c6af" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { fg = "#8ec0ab" })
hi(0, "AerialArray", { fg = "#d3c6af" })
hi(0, "AerialArrayIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialBoolean", { fg = "#d3c6af" })
hi(0, "AerialBooleanIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialClass", { fg = "#d3c6af" })
hi(0, "AerialClassIcon", { ctermfg = 121, fg = "#e4cfac" })
hi(0, "AerialConstant", { fg = "#d3c6af" })
hi(0, "AerialConstantIcon", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "AerialConstructor", { fg = "#d3c6af" })
hi(0, "AerialConstructorIcon", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "AerialEnum", { fg = "#d3c6af" })
hi(0, "AerialEnumIcon", { ctermfg = 121, fg = "#e4cfac" })
hi(0, "AerialEnumMember", { fg = "#d3c6af" })
hi(0, "AerialEnumMemberIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialEvent", { fg = "#d3c6af" })
hi(0, "AerialEventIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialField", { fg = "#d3c6af" })
hi(0, "AerialFieldIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialFile", { fg = "#d3c6af" })
hi(0, "AerialFileIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialFunction", { fg = "#d3c6af" })
hi(0, "AerialFunctionIcon", { fg = "#d297a8" })
hi(0, "AerialGuide", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide1", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide2", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide3", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide4", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide5", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide6", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide7", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide8", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialGuide9", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialInterface", { fg = "#d3c6af" })
hi(0, "AerialInterfaceIcon", { ctermfg = 121, fg = "#e4cfac" })
hi(0, "AerialKey", { fg = "#d3c6af" })
hi(0, "AerialKeyIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialLine", { bg = "#1f1f21" })
hi(0, "AerialLineNC", { bg = "#1f1f21" })
hi(0, "AerialMethod", { fg = "#d3c6af" })
hi(0, "AerialMethodIcon", { fg = "#d297a8" })
hi(0, "AerialModule", { fg = "#d3c6af" })
hi(0, "AerialModuleIcon", { fg = "#d297a8" })
hi(0, "AerialNamespace", { fg = "#d3c6af" })
hi(0, "AerialNamespaceIcon", { fg = "#d297a8" })
hi(0, "AerialNormal", { fg = "#d3c6af" })
hi(0, "AerialNormalFloat", { fg = "#d3c6af" })
hi(0, "AerialNull", { fg = "#d3c6af" })
hi(0, "AerialNullIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialNumber", { fg = "#d3c6af" })
hi(0, "AerialNumberIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialObject", { fg = "#d3c6af" })
hi(0, "AerialObjectIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialOperator", { fg = "#d3c6af" })
hi(0, "AerialOperatorIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialPackage", { fg = "#d3c6af" })
hi(0, "AerialPackageIcon", { fg = "#d297a8" })
hi(0, "AerialPrivate", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialProperty", { fg = "#d3c6af" })
hi(0, "AerialPropertyIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialProtected", { ctermfg = 14, fg = "#5d545e" })
hi(0, "AerialString", { fg = "#d3c6af" })
hi(0, "AerialStringIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialStruct", { fg = "#d3c6af" })
hi(0, "AerialStructIcon", { ctermfg = 121, fg = "#e4cfac" })
hi(0, "AerialTypeParameter", { fg = "#d3c6af" })
hi(0, "AerialTypeParameterIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "AerialVariable", { fg = "#d3c6af" })
hi(0, "AerialVariableIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "Beacon", { bg = "#c6beac" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#e7ab82" })
hi(0, "BufferCurrent", { bg = "#282829", bold = true, fg = "#d3c6af" })
hi(0, "BufferCurrentIcon", { bg = "#282829" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#282829", bold = true, fg = "#e6b8e3" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#282829", bold = true, fg = "#9db6d0" })
hi(0, "BufferInactive", { bg = "#1f1f21", fg = "#695e6b" })
hi(0, "BufferInactiveIcon", { bg = "#1f1f21" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#1f1f21", fg = "#e6b8e3" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#1f1f21", bold = true, fg = "#9db6d0" })
hi(0, "BufferLineBuffer", { fg = "#695e6b" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#d3c6af" })
hi(0, "BufferLineBufferVisible", { fg = "#d3c6af" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#b4a48e", fg = "#39313b" })
hi(0, "BufferLineTabSelected", { bg = "#b4a48e", bold = true, fg = "#39313b" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#b4a48e", bold = true, fg = "#423a45" })
hi(0, "BufferVisible", { bg = "#1f1f21", bold = true, fg = "#d3c6af" })
hi(0, "BufferVisibleIcon", { bg = "#1f1f21" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#1f1f21", bold = true, fg = "#e6b8e3" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#1f1f21", bold = true, fg = "#9db6d0" })
hi(0, "Changed", { fg = "#9db6d0" })
hi(0, "Character", { fg = "#e6b8e3" })
hi(0, "CmpGhostText", { ctermfg = 14, fg = "#5d545e" })
hi(0, "CmpItemAbbr", { fg = "#d3c6af" })
hi(0, "CmpItemAbbrDefault", { fg = "#d3c6af" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#5d545e" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#5d545e" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e4cfac" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#d3c6af" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e4cfac" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#d3c6af" })
hi(0, "CmpItemKind", { bg = "#1f1f21", fg = "#a6b8b2" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#94c5b0" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "Statement" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { bg = "#1f1f21", fg = "#d3c6af" })
hi(0, "CmpItemMenuDefault", { fg = "#d3c6af" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { fg = "#a6b8b2" })
hi(0, "CocMenuSel", { bg = "#282829" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#e4cfac" })
hi(0, "CocSelectedText", { fg = "#e6b8e3" })
hi(0, "ColorColumn", { bg = "#1f1f21", ctermbg = 1 })
hi(0, "Comment", { ctermfg = 14, fg = "#5d545e" })
hi(0, "Conceal", { ctermbg = 242, ctermfg = 7, fg = "#d297a8" })
hi(0, "Conditional", { fg = "#9db6d0" })
hi(0, "Constant", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "CurSearch", { bg = "#b68667", fg = "#423a45" })
hi(0, "Cursor", { bg = "#a39c90", fg = "#39313b" })
hi(0, "CursorColumn", { bg = "#1f1f21", ctermbg = 242 })
hi(0, "CursorIM", { bg = "#a39c90", fg = "#39313b" })
hi(0, "CursorLine", { bg = "#2a2a2c" })
hi(0, "CursorLineFold", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "CursorLineNr", { bg = "#1f1f21", ctermfg = 11, fg = "#695e6b" })
hi(0, "CursorLineSign", { bg = "#1f1f21", fg = "#5d545e" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#8ec0ab" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#9db6d0" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Title" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Debug", { fg = "#e6b8e3" })
hi(0, "Define", { fg = "#9db6d0" })
hi(0, "Definitions", { fg = "#8ec0ab" })
hi(0, "DefinitionsIcon", { fg = "#d297a8" })
hi(0, "Delimiter", { fg = "#a6b8b2" })
hi(0, "DiagnosticError", { ctermfg = 1, fg = "#e6b8e3" })
hi(0, "DiagnosticFloatingError", { bg = "#1f1f21", fg = "#e6b8e3" })
hi(0, "DiagnosticFloatingHint", { bg = "#1f1f21", fg = "#d297a8" })
hi(0, "DiagnosticFloatingInfo", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "DiagnosticFloatingOk", { bg = "#1f1f21", fg = "#8ec0ab" })
hi(0, "DiagnosticFloatingWarn", { bg = "#1f1f21", fg = "#9db6d0" })
hi(0, "DiagnosticHint", { ctermfg = 7, fg = "#d297a8" })
hi(0, "DiagnosticInfo", { ctermfg = 4, fg = "#94c5b0" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#8ec0ab" })
hi(0, "DiagnosticSignError", { link = "DiagnosticFloatingError" })
hi(0, "DiagnosticSignHint", { link = "DiagnosticFloatingHint" })
hi(0, "DiagnosticSignInfo", { link = "DiagnosticFloatingInfo" })
hi(0, "DiagnosticSignOk", { link = "DiagnosticFloatingOk" })
hi(0, "DiagnosticSignWarn", { link = "DiagnosticFloatingWarn" })
hi(0, "DiagnosticUnderlineError", { sp = "#b8aad9", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#b58385", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#7aacaa", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#8aa387", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#8e9cb4", underline = true })
hi(0, "DiagnosticWarn", { ctermfg = 3, fg = "#9db6d0" })
hi(0, "DiffAdd", { bg = "#1f1f21", ctermbg = 4, fg = "#8ec0ab" })
hi(0, "DiffChange", { bg = "#1f1f21", ctermbg = 5, fg = "#9db6d0" })
hi(0, "DiffDelete", { bg = "#1f1f21", ctermbg = 6, ctermfg = 12, fg = "#e6b8e3" })
hi(0, "DiffText", { bg = "#1f1f21", ctermbg = 9, fg = "#d297a8" })
hi(0, "Directory", { ctermfg = 159, fg = "#d297a8" })
hi(0, "EndOfBuffer", { fg = "#5d545e" })
hi(0, "Error", { bg = "#a398c1", ctermbg = 9, ctermfg = 15, fg = "#39313b" })
hi(0, "ErrorMsg", { bg = "#161619", ctermbg = 1, ctermfg = 15, fg = "#e6b8e3" })
hi(0, "Exception", { fg = "#e6b8e3" })
hi(0, "FinderParam", { fg = "#e6b8e3" })
hi(0, "FinderSpinner", { fg = "#8ec0ab" })
hi(0, "FinderSpinnerBorder", { fg = "#a6b8b2" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#e7ab82" })
-- #e6b8e3  #bfdbd0
hi(0, "FlashLabel", { fg = "#ddece5", bold = true })
hi(0, "FlashMatch", { fg = "#82628c" })
hi(0, "FlashCurrent", { fg = "#7e6fa8" })
hi(0, "FlashBackdrop", { fg = "#4a434b" })
-- hi(0, "FlashCursor", { nocombine = true })
hi(0, "Float", { fg = "#e7ab82" })
hi(0, "FoldColumn", { bg = "#1f1f21", ctermbg = 242, ctermfg = 14, fg = "#94c5b0" })
hi(0, "Folded", { bg = "#1f1f21", ctermbg = 242, ctermfg = 14, fg = "#5d545e" })
hi(0, "Function", { fg = "#d297a8" })
hi(0, "GitSignsAdd", { bg = "#1f1f21", fg = "#8ec0ab" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { bg = "#1f1f21", fg = "#9db6d0" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { bg = "#1f1f21", fg = "#e6b8e3" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsStagedAdd", { bg = "#1f1f21", fg = "#546d62" })
hi(0, "GitSignsStagedAddLn", { bg = "#1f1f21", fg = "#546d62" })
hi(0, "GitSignsStagedAddNr", { bg = "#1f1f21", fg = "#546d62" })
hi(0, "GitSignsStagedChange", { bg = "#1f1f21", fg = "#5c6875" })
hi(0, "GitSignsStagedChangeLn", { bg = "#1f1f21", fg = "#5c6875" })
hi(0, "GitSignsStagedChangeNr", { bg = "#1f1f21", fg = "#5c6875" })
hi(0, "GitSignsStagedChangedelete", { bg = "#1f1f21", fg = "#5c6875" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#1f1f21", fg = "#5c6875" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#1f1f21", fg = "#5c6875" })
hi(0, "GitSignsStagedDelete", { bg = "#1f1f21", fg = "#81697e" })
hi(0, "GitSignsStagedDeleteLn", { bg = "#1f1f21", fg = "#81697e" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#1f1f21", fg = "#81697e" })
hi(0, "GitSignsStagedTopdelete", { bg = "#1f1f21", fg = "#81697e" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#1f1f21", fg = "#81697e" })
hi(0, "GitSignsUntracked", { bg = "#1f1f21", fg = "#d297a8" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HopNextKey", { bold = true, fg = "#9db6d0", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#e6b8e3", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#695e6b", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#e7ab82", nocombine = true })
hi(0, "HopUnmatched", { link = "Comment" })
hi(0, "HydraAmaranth", { fg = "#9db6d0" })
hi(0, "HydraBlue", { fg = "#d297a8" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#e7ab82" })
hi(0, "HydraRed", { fg = "#e6b8e3" })
hi(0, "HydraTeal", { fg = "#8ec0ab" })
hi(0, "IblIndent", { fg = "#5d545e" })
hi(0, "IblScope", { bg = "#1f1f21", ctermfg = 11, fg = "#5d545e" })
hi(0, "IblWhitespace", { fg = "#5d545e" })
hi(0, "Identifier", { ctermfg = 14, fg = "#ad9cb6" })
hi(0, "Ignore", { ctermfg = 0, fg = "#94c5b0" })
hi(0, "IlluminatedWordRead", { underline = true })
hi(0, "IlluminatedWordText", { underline = true })
hi(0, "IlluminatedWordWrite", { underline = true })
hi(0, "IncSearch", { bg = "#b68667", fg = "#423a45" })
hi(0, "Include", { fg = "#d297a8" })
hi(0, "IndentBlanklineChar", { fg = "#4e444e", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#a6b8b2", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#90a0a0", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#e6b8e3", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#e7ab82", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#e4cfac", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#8ec0ab", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#94c5b0", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#d297a8", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#9db6d0", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#a6b8b2", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#9db6d0" })
hi(0, "LSOutlinePreviewBorder", { fg = "#a6b8b2" })
hi(0, "Label", { fg = "#e4cfac" })
hi(0, "LazyButton", { bg = "#1f1f21" })
hi(0, "LazyButtonActive", { bg = "#282829" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#282829", bold = true })
hi(0, "LeapLabel", { link = "Label", bold = true, nocombine = true })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabelPrimary", { bold = true, fg = "#e6b8e3", nocombine = true })
hi(0, "LeapLabelSecondary", { bold = true, fg = "#d3c6af", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#e7ab82", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#9db6d0", nocombine = true, underline = true })
hi(0, "LightspeedCursor", { link = "Cursor" })
hi(0, "LightspeedGreyWash", { link = "Comment" })
hi(0, "LightspeedLabel", { bold = true, fg = "#9db6d0", underline = true })
hi(0, "LightspeedLabelDistant", { bold = true, fg = "#d297a8", underline = true })
hi(0, "LightspeedMaskedChar", { fg = "#695e6b" })
hi(0, "LightspeedOneCharMatch", { link = "LightspeedShortcut" })
hi(0, "LightspeedPendingOpArea", { link = "IncSearch" })
hi(0, "LightspeedShortcut", { bold = true, fg = "#e9e9e9" })
hi(0, "LightspeedUniqueChar", { link = "LightspeedUnlabeledMatch" })
hi(0, "LightspeedUnlabeledMatch", { bold = true, fg = "#d3c6af" })
hi(0, "LineNr", { bg = "#1f1f21", ctermfg = 11, fg = "#5d545e" })
hi(0, "LineNrAbove", { bg = "#1f1f21", fg = "#5d545e" })
hi(0, "LineNrBelow", { bg = "#1f1f21", fg = "#5d545e" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspInfoBorder", { fg = "#e4cfac" })
hi(0, "LspInfoFiletype", { ctermfg = 121, fg = "#e4cfac" })
hi(0, "LspInfoList", { fg = "#d297a8" })
hi(0, "LspInfoTip", { ctermfg = 14, fg = "#5d545e" })
hi(0, "LspInfoTitle", { ctermfg = 225, fg = "#d297a8" })
hi(0, "LspReferenceText", { bg = "#282829" })
hi(0, "LspSagaAutoPreview", { fg = "#a6b8b2" })
hi(0, "LspSagaBorderTitle", { link = "Title" })
hi(0, "LspSagaCodeActionBorder", { fg = "#a6b8b2" })
hi(0, "LspSagaCodeActionContent", { fg = "#d3c6af" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#d297a8" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#a6b8b2" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#a6b8b2" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#9db6d0" })
hi(0, "LspSagaFinderSelection", { fg = "#e4cfac" })
hi(0, "LspSagaHoverBorder", { fg = "#a6b8b2" })
hi(0, "LspSagaLspFinderBorder", { fg = "#a6b8b2" })
hi(0, "LspSagaRenameBorder", { fg = "#a6b8b2" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#a6b8b2" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "Macro", { fg = "#e6b8e3" })
hi(0, "MasonError", { fg = "#e6b8e3" })
hi(0, "MasonHeader", { bg = "#9e7677", bold = true, fg = "#39313b" })
hi(0, "MasonHeaderSecondary", { bg = "#838e8e", bold = true, fg = "#39313b" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#a6b8b2" })
hi(0, "MasonHighlightBlock", { bg = "#838e8e", fg = "#39313b" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#9e7677", fg = "#39313b" })
hi(0, "MasonHighlightSecondary", { fg = "#d297a8" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#373737", fg = "#39313b" })
hi(0, "MasonMutedBlockBold", { bg = "#373737", bold = true, fg = "#39313b" })
hi(0, "MatchParen", { bg = "#282829", ctermbg = 6 })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "NormalFloat" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#1f1f21", bold = true, fg = "#d297a8" })
hi(0, "MiniCompletionActiveParameter", { bg = "#282829" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { bg = "#1f1f21", fg = "#8ec0ab" })
hi(0, "MiniDiffSignChange", { bg = "#1f1f21", fg = "#9db6d0" })
hi(0, "MiniDiffSignDelete", { bg = "#1f1f21", fg = "#e6b8e3" })
hi(0, "MiniFilesBorder", { link = "NormalFloat" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { bg = "#1f1f21" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#e4cfac" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { bg = "#1f1f21", fg = "#a398c1" })
hi(0, "MiniFilesTitleFocused", { bg = "#1f1f21", bold = true, fg = "#d297a8" })
hi(0, "MiniHipatternsFixme", { bg = "#a398c1", bold = true, fg = "#39313b" })
hi(0, "MiniHipatternsHack", { bg = "#808b9e", bold = true, fg = "#39313b" })
hi(0, "MiniHipatternsNote", { bg = "#9e7677", bold = true, fg = "#39313b" })
hi(0, "MiniHipatternsTodo", { bg = "#6e9997", bold = true, fg = "#39313b" })
hi(0, "MiniIndentscopeSymbol", { fg = "#a6b8b2" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#e6b8e3" })
hi(0, "MiniJump", { link = "SpellRare" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bg = "#1f1f21", bold = true, fg = "#e9e9e9", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#161619", fg = "#e7d5bb", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#1f1f21", fg = "#7aacaa" })
hi(0, "MiniMapSymbolCount", { fg = "#e7d5bb" })
hi(0, "MiniMapSymbolLine", { fg = "#d297a8" })
hi(0, "MiniMapSymbolView", { fg = "#a398c1" })
hi(0, "MiniNotifyBorder", { link = "NormalFloat" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "NormalFloat" })
hi(0, "MiniPickBorderBusy", { bg = "#1f1f21", fg = "#9db6d0" })
hi(0, "MiniPickBorderText", { bg = "#1f1f21", bold = true, fg = "#d297a8" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { fg = "#d3c6af" })
hi(0, "MiniPickMatchCurrent", { bg = "#282829" })
hi(0, "MiniPickMatchMarked", { bg = "#373737" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { bg = "#282829" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#1f1f21", fg = "#8ec0ab" })
hi(0, "MiniStarterCurrent", { fg = "#d3c6af" })
hi(0, "MiniStarterFooter", { fg = "#d297a8" })
hi(0, "MiniStarterHeader", { fg = "#d297a8" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { fg = "#d3c6af" })
hi(0, "MiniStarterItemBullet", { fg = "#a6b8b2" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#e6b8e3" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#8ec0ab" })
hi(0, "MiniStarterSection", { fg = "#a6b8b2" })
hi(0, "MiniStatuslineDevinfo", { bg = "#282829", fg = "#695e6b" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#1f1f21", fg = "#5d545e" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#8ec0ab", bold = true, fg = "#d3c6af" })
hi(0, "MiniStatuslineModeInsert", { bg = "#a398c1", bold = true, fg = "#d3c6af" })
hi(0, "MiniStatuslineModeNormal", { bg = "#9e7677", bold = true, fg = "#d3c6af" })
hi(0, "MiniStatuslineModeOther", { bg = "#9db6d0", bold = true, fg = "#d3c6af" })
hi(0, "MiniStatuslineModeReplace", { bg = "#808b9e", bold = true, fg = "#d3c6af" })
hi(0, "MiniStatuslineModeVisual", { bg = "#7d907c", bold = true, fg = "#d3c6af" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#282829", bold = true, fg = "#d3c6af" })
hi(0, "MiniTablineHidden", { bg = "#1f1f21", fg = "#695e6b" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#a39c90", bold = true, fg = "#4e444e" })
hi(0, "MiniTablineModifiedHidden", { bg = "#424242", fg = "#423a45" })
hi(0, "MiniTablineModifiedVisible", { bg = "#424242", bold = true, fg = "#4e444e" })
hi(0, "MiniTablineTabpagesection", { bg = "#b4a48e", bold = true, fg = "#423a45" })
hi(0, "MiniTablineVisible", { bg = "#1f1f21", bold = true, fg = "#d3c6af" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#e6b8e3" })
hi(0, "MiniTestPass", { bold = true, fg = "#8ec0ab" })
hi(0, "MiniTrailspace", { link = "Error" })
hi(0, "ModeMsg", { fg = "#8ec0ab" })
hi(0, "MoreMsg", { ctermfg = 121, fg = "#8ec0ab" })
hi(0, "MsgArea", { bg = "#161619", fg = "#d3c6af" })
hi(0, "MsgSeparator", { bg = "#282829", fg = "#695e6b" })
hi(0, "NeoTreeDimText", { fg = "#5d545e" })
hi(0, "NeoTreeDotfile", { fg = "#695e6b" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#4e444e" })
hi(0, "NeoTreeFileNameOpened", { bold = true })
hi(0, "NeoTreeFileStats", { fg = "#737067" })
hi(0, "NeoTreeFileStatsHeader", { bold = true, fg = "#84656f" })
hi(0, "NeoTreeFloatTitle", { bg = "#282829", fg = "#d3c6af" })
hi(0, "NeoTreeGitAdded", { fg = "#8ec0ab" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#e6b8e3" })
hi(0, "NeoTreeGitDeleted", { fg = "#e6b8e3" })
hi(0, "NeoTreeGitModified", { fg = "#9db6d0" })
hi(0, "NeoTreeGitUnstaged", { fg = "#e6b8e3" })
hi(0, "NeoTreeGitUntracked", { fg = "#e4cfac" })
hi(0, "NeoTreeMessage", { bg = "#1f1f21", fg = "#d3c6af" })
hi(0, "NeoTreeModified", { fg = "#e9e9e9" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#d297a8" })
hi(0, "NeoTreeTabActive", { bold = true })
hi(0, "NeoTreeTabInactive", { fg = "#695e6b" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#282829", fg = "#5d545e" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#1f1f21", fg = "#423a45" })
hi(0, "NeoTreeTitleBar", { bg = "#282829", fg = "#39313b" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#d297a8" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#d297a8" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceAttr122", { bg = "#161619", fg = "#e6b8e3" })
hi(0, "NoiceCmdline", { bg = "#161619", fg = "#d3c6af" })
hi(0, "NoiceCmdlineIcon", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "NoiceCmdlineIconCalculator", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "NoiceCmdlineIconCmdline", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "NoiceCmdlineIconFilter", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "NoiceCmdlineIconHelp", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "NoiceCmdlineIconInput", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "NoiceCmdlineIconLua", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "NoiceCmdlineIconSearch", { bg = "#1f1f21", fg = "#9db6d0" })
hi(0, "NoiceCmdlinePopup", { bg = "#161619", fg = "#d3c6af" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#d297a8" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#d297a8" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#d297a8" })
hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#d297a8" })
hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#d297a8" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#d297a8" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#d297a8" })
hi(0, "NoiceCmdlinePopupBorderSearch", { bg = "#1f1f21", fg = "#9db6d0" })
hi(0, "NoiceCmdlinePopupTitle", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "NoiceCmdlinePrompt", { ctermfg = 225, fg = "#d297a8" })
hi(0, "NoiceCompletionItemKindClass", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindColor", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindConstant", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindConstructor", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindDefault", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindEnum", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindEnumMember", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindField", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindFile", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindFolder", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindFunction", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindInterface", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindKeyword", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindMethod", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindModule", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindProperty", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindSnippet", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindStruct", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindText", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindUnit", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindValue", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceCompletionItemKindVariable", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceConfirm", { bg = "#161619", fg = "#d3c6af" })
hi(0, "NoiceConfirmBorder", { fg = "#9db6d0" })
hi(0, "NoiceCursor", { bg = "#a39c90", fg = "#39313b" })
hi(0, "NoiceFormatConfirm", { bg = "#1f1f21" })
hi(0, "NoiceFormatConfirmDefault", { bg = "#282829", ctermbg = 242 })
hi(0, "NoiceFormatDate", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoiceFormatEvent", { ctermfg = 12, fg = "#5d545e" })
hi(0, "NoiceFormatKind", { ctermfg = 12, fg = "#5d545e" })
hi(0, "NoiceFormatLevelDebug", { ctermfg = 12, fg = "#5d545e" })
hi(0, "NoiceFormatLevelError", { ctermfg = 1, fg = "#e6b8e3" })
hi(0, "NoiceFormatLevelInfo", { ctermfg = 4, fg = "#94c5b0" })
hi(0, "NoiceFormatLevelOff", { ctermfg = 12, fg = "#5d545e" })
hi(0, "NoiceFormatLevelTrace", { ctermfg = 12, fg = "#5d545e" })
hi(0, "NoiceFormatLevelWarn", { ctermfg = 3, fg = "#9db6d0" })
hi(0, "NoiceFormatProgressDone", { bg = "#b4a48e", fg = "#423a45" })
hi(0, "NoiceFormatProgressTodo", { bg = "#1f1f21" })
hi(0, "NoiceFormatTitle", { ctermfg = 225, fg = "#d297a8" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { ctermfg = 225, fg = "#d297a8" })
hi(0, "NoiceLspProgressSpinner", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "NoiceLspProgressTitle", { ctermfg = 12, fg = "#5d545e" })
hi(0, "NoiceMini", { bg = "#161619", fg = "#d3c6af" })
hi(0, "NoicePopup", { bg = "#1f1f21", fg = "#d3c6af" })
hi(0, "NoicePopupBorder", { bg = "#282829", fg = "#4e444e" })
hi(0, "NoicePopupmenu", { bg = "#1f1f21", ctermbg = 13, ctermfg = 0, fg = "#d3c6af" })
hi(0, "NoicePopupmenuBorder", { bg = "#282829", fg = "#4e444e" })
hi(0, "NoicePopupmenuMatch", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "NoicePopupmenuSelected", { bg = "#a39c90", ctermbg = 0, ctermfg = 242, fg = "#423a45" })
hi(0, "NoiceScrollbar", { bg = "#282829", ctermbg = 248 })
hi(0, "NoiceScrollbarThumb", { bg = "#c6beac", ctermbg = 15 })
hi(0, "NoiceSplit", { bg = "#1f1f21", fg = "#d3c6af" })
hi(0, "NoiceSplitBorder", { bg = "#282829", fg = "#4e444e" })
hi(0, "NoiceVirtualText", { ctermfg = 4, fg = "#94c5b0" })
hi(0, "NonText", { ctermfg = 12, fg = "#5d545e" })
hi(0, "Normal", { bg = "#232326", fg = "#d3c6af" })
hi(0, "NormalFloat", { bg = "#1f1f21", fg = "#d3c6af" })
hi(0, "NormalNC", { bg = "#161619", fg = "#d3c6af" })
hi(0, "NotifyDEBUGBorder", { fg = "#5d545e" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBody24", { link = "NotifyERRORBody" })
hi(0, "NotifyERRORBody363", { link = "NotifyERRORBody" })
hi(0, "NotifyERRORBody41", { link = "NotifyERRORBody" })
hi(0, "NotifyERRORBody58", { link = "NotifyERRORBody" })
hi(0, "NotifyERRORBorder", { fg = "#e6b8e3" })
hi(0, "NotifyERRORBorder24", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORBorder363", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORBorder41", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORBorder58", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORIcon24", { link = "NotifyERRORIcon" })
hi(0, "NotifyERRORIcon363", { link = "NotifyERRORIcon" })
hi(0, "NotifyERRORIcon41", { link = "NotifyERRORIcon" })
hi(0, "NotifyERRORIcon58", { link = "NotifyERRORIcon" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle24", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle363", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle41", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle58", { link = "NotifyERRORTitle" })
hi(0, "NotifyINFOBorder", { fg = "#94c5b0" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#d297a8" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#9db6d0" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "Number", { fg = "#e6b8e3" })
hi(0, "NvimInternalError", { bg = "#e50001", ctermbg = 9, ctermfg = 9, fg = "#e77482" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#8ec0ab" })
hi(0, "NvimTreeFolderIcon", { fg = "#5d545e" })
hi(0, "NvimTreeGitDeleted", { fg = "#e6b8e3" })
hi(0, "NvimTreeGitDirty", { fg = "#e6b8e3" })
hi(0, "NvimTreeGitMerge", { fg = "#94c5b0" })
hi(0, "NvimTreeGitNew", { fg = "#e4cfac" })
hi(0, "NvimTreeGitRenamed", { fg = "#9db6d0" })
hi(0, "NvimTreeGitStaged", { fg = "#8ec0ab" })
hi(0, "NvimTreeImageFile", { bold = true, fg = "#9db6d0" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { link = "NvimTreeGitRenamed" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#d297a8", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#a6b8b2" })
hi(0, "NvimTreeWindowPicker", { bg = "#1f1f21", bold = true, fg = "#d3c6af" })
hi(0, "Operator", { fg = "#959daf", bold = true })
hi(0, "OutlineDetail", { fg = "#5d545e" })
hi(0, "OutlineFoldPrefix", { fg = "#e6b8e3" })
hi(0, "OutlineIndentEvn", { fg = "#695e6b" })
hi(0, "OutlineIndentOdd", { fg = "#d3c6af" })
hi(0, "Pmenu", { bg = "#1f1f21", ctermbg = 13, ctermfg = 0, fg = "#d3c6af" })
hi(0, "PmenuSbar", { bg = "#282829", ctermbg = 248 })
hi(0, "PmenuSel", { bg = "#a39c90", ctermbg = 0, ctermfg = 242, fg = "#423a45" })
hi(0, "PmenuThumb", { bg = "#c6beac", ctermbg = 15 })
hi(0, "PounceAccept", { bg = "#a398c1", bold = true, fg = "#39313b", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#7d907c", bold = true, fg = "#39313b", nocombine = true })
hi(0, "PounceGap", { bg = "#373737", bold = true, fg = "#39313b", nocombine = true })
hi(0, "PounceMatch", { bg = "#a39c90", bold = true, fg = "#39313b", nocombine = true })
hi(0, "PreCondit", { fg = "#e4cfac" })
hi(0, "PreProc", { ctermfg = 81, fg = "#e4cfac" })
hi(0, "Question", { ctermfg = 121, fg = "#d297a8" })
hi(0, "QuickFixLine", { bg = "#1f1f21" })
hi(0, "RainbowDelimiterBlue", { fg = "#d297a8" })
hi(0, "RainbowDelimiterCyan", { fg = "#94c5b0" })
hi(0, "RainbowDelimiterGreen", { fg = "#8ec0ab" })
hi(0, "RainbowDelimiterOrange", { fg = "#e7ab82" })
hi(0, "RainbowDelimiterRed", { fg = "#e6b8e3" })
hi(0, "RainbowDelimiterViolet", { fg = "#9db6d0" })
hi(0, "RainbowDelimiterYellow", { fg = "#e4cfac" })
hi(0, "RedrawDebugClear", { bg = "#e3e402", ctermbg = 11 })
hi(0, "RedrawDebugComposed", { bg = "#007500", ctermbg = 10 })
hi(0, "RedrawDebugRecompose", { bg = "#e50001", ctermbg = 9 })
hi(0, "References", { fg = "#8ec0ab" })
hi(0, "ReferencesIcon", { fg = "#d297a8" })
hi(0, "Removed", { fg = "#e6b8e3" })
hi(0, "Repeat", { fg = "#e4cfac" })
hi(0, "Search", { bg = "#808b9e", ctermbg = 11, ctermfg = 0, fg = "#c6beac" })
hi(0, "SignColumn", { bg = "#1f1f21", ctermbg = 242, ctermfg = 14, fg = "#5d545e" })
hi(0, "Sneak", { bg = "#808b9e", fg = "#39313b" })
hi(0, "SneakLabel", { bg = "#808b9e", bold = true, fg = "#39313b" })
hi(0, "SneakScope", { bg = "#c6beac", fg = "#39313b" })
hi(0, "Special", { ctermfg = 8, fg = "#94c5b0" })
hi(0, "SpecialChar", { fg = "#a6b8b2" })
hi(0, "SpecialComment", { fg = "#bd94bc" })
hi(0, "SpecialKey", { ctermfg = 81, fg = "#5d545e" })
hi(0, "SpellBad", { ctermbg = 9, sp = "#b8aad9", undercurl = true })
hi(0, "SpellCap", { ctermbg = 12, sp = "#b58385", undercurl = true })
hi(0, "SpellLocal", { ctermbg = 14, sp = "#7aacaa", undercurl = true })
hi(0, "SpellRare", { ctermbg = 13, sp = "#8e9cb4", undercurl = true })
hi(0, "Statement", { ctermfg = 11, fg = "#e6b8e3" })
hi(0, "StatusLine", { bg = "#282829", fg = "#695e6b" })
hi(0, "StatusLineNC", { bg = "#1f1f21", fg = "#5d545e" })
hi(0, "StorageClass", { fg = "#e4cfac" })
hi(0, "String", { fg = "#a7c5af", italic = true })
hi(0, "Structure", { fg = "#9db6d0" })
hi(0, "Substitute", { bg = "#b4a48e", fg = "#423a45" })
hi(0, "TabLine", { bg = "#1f1f21", ctermbg = 242, ctermfg = 15, fg = "#5d545e" })
hi(0, "TabLineFill", { bg = "#1f1f21", fg = "#5d545e" })
hi(0, "TabLineSel", { bg = "#1f1f21", fg = "#8ec0ab" })
hi(0, "Tag", { fg = "#e4cfac" })
hi(0, "TargetFileName", { fg = "#d3c6af" })
hi(0, "TelescopeBorder", { fg = "#a6b8b2" })
hi(0, "TelescopeMatching", { fg = "#e4cfac" })
hi(0, "TelescopeMultiIcon", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "TelescopeMultiSelection", { bg = "#1f1f21", bold = true })
hi(0, "TelescopeNormal", { bg = "#161619", fg = "#d3c6af" })
hi(0, "TelescopePreviewBlock", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "TelescopePreviewBorder", { fg = "#a6b8b2" })
hi(0, "TelescopePreviewCharDev", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "TelescopePreviewDate", { ctermfg = 159, fg = "#d297a8" })
hi(0, "TelescopePreviewDirectory", { ctermfg = 159, fg = "#d297a8" })
hi(0, "TelescopePreviewExecute", { fg = "#8ec0ab" })
hi(0, "TelescopePreviewGroup", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "TelescopePreviewHyphen", { ctermfg = 12, fg = "#5d545e" })
hi(0, "TelescopePreviewLine", { bg = "#282829", ctermbg = 242 })
hi(0, "TelescopePreviewLink", { ctermfg = 224, fg = "#94c5b0" })
hi(0, "TelescopePreviewMatch", { bg = "#b4a48e", ctermbg = 11, ctermfg = 0, fg = "#423a45" })
hi(0, "TelescopePreviewMessage", { bg = "#161619", fg = "#d3c6af" })
hi(0, "TelescopePreviewMessageFillchar", { bg = "#161619", fg = "#d3c6af" })
hi(0, "TelescopePreviewNormal", { bg = "#161619", fg = "#d3c6af" })
hi(0, "TelescopePreviewPipe", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "TelescopePreviewRead", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "TelescopePreviewSize", { fg = "#8ec0ab" })
hi(0, "TelescopePreviewSocket", { ctermfg = 11, fg = "#e6b8e3" })
hi(0, "TelescopePreviewSticky", { fg = "#9db6d0" })
hi(0, "TelescopePreviewTitle", { fg = "#a6b8b2" })
hi(0, "TelescopePreviewUser", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "TelescopePreviewWrite", { ctermfg = 11, fg = "#e6b8e3" })
hi(0, "TelescopePromptBorder", { fg = "#a6b8b2" })
hi(0, "TelescopePromptCounter", { ctermfg = 12, fg = "#5d545e" })
hi(0, "TelescopePromptNormal", { bg = "#161619", fg = "#d3c6af" })
hi(0, "TelescopePromptPrefix", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "TelescopePromptTitle", { fg = "#a6b8b2" })
hi(0, "TelescopeResultsBorder", { fg = "#a6b8b2" })
hi(0, "TelescopeResultsClass", { fg = "#d297a8" })
hi(0, "TelescopeResultsComment", { ctermfg = 14, fg = "#5d545e" })
hi(0, "TelescopeResultsConstant", { ctermfg = 13, fg = "#e7ab82" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#1f1f21", ctermbg = 4, fg = "#8ec0ab" })
hi(0, "TelescopeResultsDiffChange", { bg = "#1f1f21", ctermbg = 5, fg = "#9db6d0" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#1f1f21", ctermbg = 6, ctermfg = 12, fg = "#e6b8e3" })
hi(0, "TelescopeResultsDiffUntracked", { ctermfg = 12, fg = "#5d545e" })
hi(0, "TelescopeResultsField", { fg = "#d297a8" })
hi(0, "TelescopeResultsFunction", { fg = "#d297a8" })
hi(0, "TelescopeResultsIdentifier", { ctermfg = 14, fg = "#e6b8e3" })
hi(0, "TelescopeResultsLineNr", { bg = "#1f1f21", ctermfg = 11, fg = "#5d545e" })
hi(0, "TelescopeResultsNormal", { bg = "#161619", fg = "#d3c6af" })
hi(0, "TelescopeResultsNumber", { fg = "#e7ab82" })
hi(0, "TelescopeResultsOperator", { fg = "#d3c6af" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#94c5b0" })
hi(0, "TelescopeResultsTitle", { fg = "#a6b8b2" })
hi(0, "TelescopeResultsVariable", { fg = "#a6b8b2" })
hi(0, "TelescopeSelection", { bg = "#1f1f21", bold = true })
hi(0, "TelescopeSelectionCaret", { bg = "#1f1f21", bold = true })
hi(0, "TelescopeTitle", { fg = "#a6b8b2" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { ctermfg = 225, fg = "#d297a8" })
hi(0, "Todo", { bg = "#1f1f21", ctermbg = 11, ctermfg = 0, fg = "#e4cfac" })
hi(0, "TodoBgFIX", { bg = "#a398c1", bold = true, fg = "#39313b" })
hi(0, "TodoBgHACK", { bg = "#808b9e", bold = true, fg = "#39313b" })
hi(0, "TodoBgNOTE", { bg = "#9e7677", bold = true, fg = "#39313b" })
hi(0, "TodoBgPERF", { bg = "#a398c1", bold = true, fg = "#39313b" })
hi(0, "TodoBgTEST", { bg = "#a398c1", bold = true, fg = "#39313b" })
hi(0, "TodoBgTODO", { bg = "#6e9997", bold = true, fg = "#39313b" })
hi(0, "TodoBgWARN", { bg = "#808b9e", bold = true, fg = "#39313b" })
hi(0, "TodoFgFIX", { fg = "#e6b8e3" })
hi(0, "TodoFgHACK", { fg = "#9db6d0" })
hi(0, "TodoFgNOTE", { fg = "#d297a8" })
hi(0, "TodoFgPERF", { fg = "#e6b8e3" })
hi(0, "TodoFgTEST", { fg = "#e6b8e3" })
hi(0, "TodoFgTODO", { fg = "#94c5b0" })
hi(0, "TodoFgWARN", { fg = "#9db6d0" })
hi(0, "TodoSignFIX", { bg = "#1f1f21", fg = "#e6b8e3" })
hi(0, "TodoSignHACK", { bg = "#1f1f21", fg = "#9db6d0" })
hi(0, "TodoSignNOTE", { bg = "#1f1f21", fg = "#d297a8" })
hi(0, "TodoSignPERF", { bg = "#1f1f21", fg = "#e6b8e3" })
hi(0, "TodoSignTEST", { bg = "#1f1f21", fg = "#e6b8e3" })
hi(0, "TodoSignTODO", { bg = "#1f1f21", fg = "#94c5b0" })
hi(0, "TodoSignWARN", { bg = "#1f1f21", fg = "#9db6d0" })
hi(0, "TooLong", { fg = "#e6b8e3" })
hi(0, "TreesitterContext", { bg = "#1f1f21", fg = "#d3c6af" })
hi(0, "TreesitterContextLineNumber", { bg = "#1f1f21", ctermfg = 11, fg = "#5d545e" })
hi(0, "TreesitterContextSeparator", { bg = "#282829", fg = "#4e444e" })
hi(0, "TroubleCount", { bold = true, fg = "#8ec0ab" })
hi(0, "TroubleFoldIcon", { fg = "#d3c6af" })
hi(0, "TroubleIndent", { fg = "#4e444e" })
hi(0, "TroubleLocation", { fg = "#695e6b" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleStatusline0", { bg = "#2c2c2d", fg = "#d297a8" })
hi(0, "TroubleStatusline1", { bg = "#2c2c2d", fg = "#d3c6af" })
hi(0, "TroubleText", { fg = "#d3c6af" })
hi(0, "Type", { ctermfg = 121, fg = "#e4cfac" })
hi(0, "Typedef", { fg = "#e4cfac" })
hi(0, "Underlined", { ctermfg = 81, underline = true })
hi(0, "VertSplit", { bg = "#282829", fg = "#4e444e" })
hi(0, "Visual", { bg = "#282829", ctermbg = 242 })
hi(0, "VisualNOS", { fg = "#e6b8e3" })
hi(0, "WarningMsg", { ctermfg = 224, fg = "#e6b8e3" })
hi(0, "WhichKey", { fg = "#d297a8" })
hi(0, "WhichKeyBorder", { bg = "#282829", fg = "#4e444e" })
hi(0, "WhichKeyDesc", { fg = "#d3c6af" })
hi(0, "WhichKeyFloat", { bg = "#1f1f21", fg = "#d3c6af" })
hi(0, "WhichKeyGroup", { fg = "#9db6d0" })
hi(0, "WhichKeySeparator", { bg = "#1f1f21", fg = "#8ec0ab" })
hi(0, "WhichKeyValue", { fg = "#5d545e" })
hi(0, "Whitespace", { fg = "#5d545e" })
hi(0, "WildMenu", { bg = "#b4a48e", ctermbg = 11, ctermfg = 0, fg = "#e6b8e3" })
hi(0, "WinBar", { bg = "#282829", fg = "#695e6b" })
hi(0, "WinBarNC", { bg = "#1f1f21", fg = "#5d545e" })
hi(0, "WinSeparator", { bg = "#282829", fg = "#4e444e" })
hi(0, "diffAdded", { fg = "#8ec0ab" })
hi(0, "diffChanged", { fg = "#9db6d0" })
hi(0, "diffFile", { fg = "#e7ab82" })
hi(0, "diffLine", { fg = "#94c5b0" })
hi(0, "diffRemoved", { fg = "#e6b8e3" })
hi(0, "gitcommitBranch", { bold = true, fg = "#e7ab82" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#e6b8e3" })
hi(0, "gitcommitDiscardedType", { fg = "#d297a8" })
hi(0, "gitcommitHeader", { fg = "#9db6d0" })
hi(0, "gitcommitOverflow", { fg = "#e6b8e3" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#8ec0ab" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#8ec0ab" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#e4cfac" })
hi(0, "lCursor", { bg = "#a39c90", fg = "#39313b" })
hi(0, "lualine_a_command", { bg = "#d7a7d4", bold = true, fg = "#343438" })
hi(0, "lualine_a_inactive", { bg = "#b3ab9e", bold = true, fg = "#343438" })
hi(0, "lualine_a_insert", { bg = "#79ae98", bold = true, fg = "#343438" })
hi(0, "lualine_a_normal", { bg = "#b3ab9e", bold = true, fg = "#343438" })
hi(0, "lualine_a_replace", { bg = "#da986c", bold = true, fg = "#343438" })
hi(0, "lualine_a_terminal", { bg = "#d7a7d4", bold = true, fg = "#343438" })
hi(0, "lualine_a_visual", { bg = "#7fb49e", bold = true, fg = "#343438" })
hi(0, "lualine_b_command", { bg = "#18181b", fg = "#e8d1e8" })
hi(0, "lualine_b_inactive", { bg = "#18181b", fg = "#d4ccbe" })
hi(0, "lualine_b_insert", { bg = "#18181b", fg = "#99cfb8" })
hi(0, "lualine_b_normal", { bg = "#18181b", fg = "#d4ccbe" })
hi(0, "lualine_b_replace", { bg = "#18181b", fg = "#e8bfa3" })
hi(0, "lualine_b_terminal", { bg = "#18181b", fg = "#e8d1e8" })
hi(0, "lualine_b_visual", { bg = "#18181b", fg = "#9fd5be" })
hi(0, "lualine_c_12_LV_Bold_command", { bg = "#2c2c2d", bold = true, fg = "#e5d6bd" })
hi(0, "lualine_c_12_LV_Bold_inactive", { bg = "#2c2c2d", bold = true, fg = "#e5d6bd" })
hi(0, "lualine_c_12_LV_Bold_insert", { bg = "#2c2c2d", bold = true, fg = "#e5d6bd" })
hi(0, "lualine_c_12_LV_Bold_normal", { bg = "#2c2c2d", bold = true, fg = "#e5d6bd" })
hi(0, "lualine_c_12_LV_Bold_replace", { bg = "#2c2c2d", bold = true, fg = "#e5d6bd" })
hi(0, "lualine_c_12_LV_Bold_terminal", { bg = "#2c2c2d", bold = true, fg = "#e5d6bd" })
hi(0, "lualine_c_12_LV_Bold_visual", { bg = "#2c2c2d", bold = true, fg = "#e5d6bd" })
hi(0, "lualine_c_9_command", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_9_inactive", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_9_insert", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_9_normal", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_9_replace", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_9_terminal", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_9_visual", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_aerial_LLNonText_command", { bg = "#2c2c2e", fg = "#5d545e" })
hi(0, "lualine_c_aerial_LLNonText_inactive", { bg = "#2c2c2e", fg = "#5d545e" })
hi(0, "lualine_c_aerial_LLNonText_insert", { bg = "#2c2c2e", fg = "#5d545e" })
hi(0, "lualine_c_aerial_LLNonText_normal", { bg = "#2c2c2e", fg = "#5d545e" })
hi(0, "lualine_c_aerial_LLNonText_replace", { bg = "#2c2c2e", fg = "#5d545e" })
hi(0, "lualine_c_aerial_LLNonText_terminal", { bg = "#2c2c2e", fg = "#5d545e" })
hi(0, "lualine_c_aerial_LLNonText_visual", { bg = "#2c2c2e", fg = "#5d545e" })
hi(0, "lualine_c_command", { bg = "#2c2c2d", fg = "#e5d6bd" })
hi(0, "lualine_c_diagnostics_error_command", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_c_diagnostics_error_inactive", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_c_diagnostics_error_insert", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_c_diagnostics_error_normal", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_c_diagnostics_error_replace", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_c_diagnostics_error_terminal", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_c_diagnostics_error_visual", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_c_diagnostics_hint_command", { bg = "#2c2c2d", fg = "#d297a8" })
hi(0, "lualine_c_diagnostics_hint_inactive", { bg = "#2c2c2d", fg = "#d297a8" })
hi(0, "lualine_c_diagnostics_hint_insert", { bg = "#2c2c2d", fg = "#d297a8" })
hi(0, "lualine_c_diagnostics_hint_normal", { bg = "#2c2c2d", fg = "#d297a8" })
hi(0, "lualine_c_diagnostics_hint_replace", { bg = "#2c2c2d", fg = "#d297a8" })
hi(0, "lualine_c_diagnostics_hint_terminal", { bg = "#2c2c2d", fg = "#d297a8" })
hi(0, "lualine_c_diagnostics_hint_visual", { bg = "#2c2c2d", fg = "#d297a8" })
hi(0, "lualine_c_diagnostics_info_command", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_diagnostics_info_inactive", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_diagnostics_info_insert", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_diagnostics_info_normal", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_diagnostics_info_replace", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_diagnostics_info_terminal", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_diagnostics_info_visual", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_c_diagnostics_warn_command", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_c_diagnostics_warn_inactive", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_c_diagnostics_warn_insert", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_c_diagnostics_warn_normal", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_c_diagnostics_warn_replace", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_c_diagnostics_warn_terminal", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_c_diagnostics_warn_visual", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_c_filetype_DevIconDefault_command", { bg = "#2c2c2d", fg = "#8c9fa6" })
hi(0, "lualine_c_filetype_DevIconDefault_inactive", { bg = "#2c2c2d", fg = "#8c9fa6" })
hi(0, "lualine_c_filetype_DevIconDefault_insert", { bg = "#2c2c2d", fg = "#8c9fa6" })
hi(0, "lualine_c_filetype_DevIconDefault_normal", { bg = "#2c2c2d", fg = "#8c9fa6" })
hi(0, "lualine_c_filetype_DevIconDefault_replace", { bg = "#2c2c2d", fg = "#8c9fa6" })
hi(0, "lualine_c_filetype_DevIconDefault_terminal", { bg = "#2c2c2d", fg = "#8c9fa6" })
hi(0, "lualine_c_filetype_DevIconDefault_visual", { bg = "#2c2c2d", fg = "#8c9fa6" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_4_command", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_4_inactive", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_4_insert", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_4_normal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_4_replace", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_4_terminal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_4_visual", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_command", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_inactive", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_insert", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_normal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_replace", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_terminal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_3_visual", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_command", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_inactive", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_insert", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_normal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_replace", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_terminal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_2_visual", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_command", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_inactive", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_insert", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_normal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_replace", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_terminal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_1_visual", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_command", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_inactive", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_insert", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_normal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_replace", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_terminal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_0_visual", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_command", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_inactive", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_insert", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_normal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_replace", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_terminal", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconLua_visual", { bg = "#2c2c2d", fg = "#7dc0e8" })
hi(0, "lualine_c_filetype_DevIconR_command", { bg = "#2c2c2d", fg = "#4386dd" })
hi(0, "lualine_c_filetype_DevIconR_inactive", { bg = "#2c2c2d", fg = "#4386dd" })
hi(0, "lualine_c_filetype_DevIconR_insert", { bg = "#2c2c2d", fg = "#4386dd" })
hi(0, "lualine_c_filetype_DevIconR_normal", { bg = "#2c2c2d", fg = "#4386dd" })
hi(0, "lualine_c_filetype_DevIconR_replace", { bg = "#2c2c2d", fg = "#4386dd" })
hi(0, "lualine_c_filetype_DevIconR_terminal", { bg = "#2c2c2d", fg = "#4386dd" })
hi(0, "lualine_c_filetype_DevIconR_visual", { bg = "#2c2c2d", fg = "#4386dd" })
hi(0, "lualine_c_inactive", { bg = "#2c2c2d", fg = "#e5d6bd" })
hi(0, "lualine_c_insert", { bg = "#2c2c2d", fg = "#e5d6bd" })
hi(0, "lualine_c_normal", { bg = "#2c2c2d", fg = "#e5d6bd" })
hi(0, "lualine_c_replace", { bg = "#2c2c2d", fg = "#e5d6bd" })
hi(0, "lualine_c_terminal", { bg = "#2c2c2d", fg = "#e5d6bd" })
hi(0, "lualine_c_visual", { bg = "#2c2c2d", fg = "#e5d6bd" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#18181b", fg = "#e8d1e8" })
hi(0, "lualine_transitional_lualine_a_insert_to_lualine_b_insert", { bg = "#18181b", fg = "#99cfb8" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#18181b", fg = "#d4ccbe" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_c_normal", { bg = "#2c2c2e", fg = "#e5d6bd" })
hi(0, "lualine_transitional_lualine_a_visual_to_lualine_b_visual", { bg = "#18181b", fg = "#9fd5be" })
hi(
	0,
	"lualine_transitional_lualine_b_command_to_lualine_c_diagnostics_warn_command",
	{ bg = "#2c2c2d", fg = "#343438" }
)
hi(
	0,
	"lualine_transitional_lualine_b_command_to_lualine_c_filetype_DevIconLua_0_1_2_3_4_command",
	{ bg = "#2c2c2d", fg = "#18181b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_command_to_lualine_c_filetype_DevIconLua_0_1_2_3_command",
	{ bg = "#2c2c2d", fg = "#1b1b1b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_command_to_lualine_c_filetype_DevIconLua_0_1_2_command",
	{ bg = "#2c2c2d", fg = "#1b1b1b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_command_to_lualine_c_filetype_DevIconLua_0_1_command",
	{ bg = "#2c2c2d", fg = "#343438" }
)
hi(
	0,
	"lualine_transitional_lualine_b_command_to_lualine_c_filetype_DevIconLua_0_command",
	{ bg = "#2c2c2d", fg = "#1b1b1b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_command_to_lualine_c_filetype_DevIconLua_command",
	{ bg = "#2c2c2d", fg = "#343438" }
)
hi(0, "lualine_transitional_lualine_b_command_to_lualine_x_4_command", { bg = "#2c2c2d", fg = "#343438" })
hi(
	0,
	"lualine_transitional_lualine_b_insert_to_lualine_c_filetype_DevIconDefault_insert",
	{ bg = "#2c2c2d", fg = "#343438" }
)
hi(
	0,
	"lualine_transitional_lualine_b_insert_to_lualine_c_filetype_DevIconLua_insert",
	{ bg = "#2c2c2d", fg = "#343438" }
)
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_x_4_insert", { bg = "#2c2c2d", fg = "#343438" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_diagnostics_warn_normal", { bg = "#2c2c2d", fg = "#343438" })
hi(
	0,
	"lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconDefault_normal",
	{ bg = "#2c2c2e", fg = "#3c333b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconLua_0_1_2_3_4_normal",
	{ bg = "#2c2c2d", fg = "#18181b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconLua_0_1_2_3_normal",
	{ bg = "#2c2c2d", fg = "#1b1b1b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconLua_0_1_2_normal",
	{ bg = "#2c2c2d", fg = "#1b1b1b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconLua_0_1_normal",
	{ bg = "#2c2c2d", fg = "#343438" }
)
hi(
	0,
	"lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconLua_0_normal",
	{ bg = "#2c2c2d", fg = "#1b1b1b" }
)
hi(
	0,
	"lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconLua_normal",
	{ bg = "#2c2c2d", fg = "#343438" }
)
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconR_normal", { bg = "#2c2c2d", fg = "#343438" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_4_normal", { bg = "#2c2c2d", fg = "#343438" })
hi(
	0,
	"lualine_transitional_lualine_b_visual_to_lualine_c_filetype_DevIconLua_visual",
	{ bg = "#2c2c2d", fg = "#343438" }
)
hi(0, "lualine_transitional_lualine_b_visual_to_lualine_x_4_visual", { bg = "#2c2c2d", fg = "#343438" })
hi(0, "lualine_x_4_command", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_4_inactive", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_4_insert", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_4_normal", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_4_replace", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_4_terminal", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_4_visual", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_5_command", { bg = "#2c2c2d", fg = "#e7ab82" })
hi(0, "lualine_x_5_inactive", { bg = "#2c2c2d", fg = "#e7ab82" })
hi(0, "lualine_x_5_insert", { bg = "#2c2c2d", fg = "#e7ab82" })
hi(0, "lualine_x_5_normal", { bg = "#2c2c2d", fg = "#e7ab82" })
hi(0, "lualine_x_5_replace", { bg = "#2c2c2d", fg = "#e7ab82" })
hi(0, "lualine_x_5_terminal", { bg = "#2c2c2d", fg = "#e7ab82" })
hi(0, "lualine_x_5_visual", { bg = "#2c2c2d", fg = "#e7ab82" })
hi(0, "lualine_x_6_command", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_6_inactive", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_6_insert", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_6_normal", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_6_replace", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_6_terminal", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_6_visual", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_7_command", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_x_7_inactive", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_x_7_insert", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_x_7_normal", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_x_7_replace", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_x_7_terminal", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_x_7_visual", { bg = "#2c2c2d", fg = "#94c5b0" })
hi(0, "lualine_x_diff_added_command", { bg = "#2c2c2d", fg = "#8ec0ab" })
hi(0, "lualine_x_diff_added_inactive", { bg = "#2c2c2d", fg = "#8ec0ab" })
hi(0, "lualine_x_diff_added_insert", { bg = "#2c2c2d", fg = "#8ec0ab" })
hi(0, "lualine_x_diff_added_normal", { bg = "#2c2c2d", fg = "#8ec0ab" })
hi(0, "lualine_x_diff_added_replace", { bg = "#2c2c2d", fg = "#8ec0ab" })
hi(0, "lualine_x_diff_added_terminal", { bg = "#2c2c2d", fg = "#8ec0ab" })
hi(0, "lualine_x_diff_added_visual", { bg = "#2c2c2d", fg = "#8ec0ab" })
hi(0, "lualine_x_diff_modified_command", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_x_diff_modified_inactive", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_x_diff_modified_insert", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_x_diff_modified_normal", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_x_diff_modified_replace", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_x_diff_modified_terminal", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_x_diff_modified_visual", { bg = "#2c2c2d", fg = "#9db6d0" })
hi(0, "lualine_x_diff_removed_command", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_diff_removed_inactive", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_diff_removed_insert", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_diff_removed_normal", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_diff_removed_replace", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_diff_removed_terminal", { bg = "#2c2c2d", fg = "#e6b8e3" })
hi(0, "lualine_x_diff_removed_visual", { bg = "#2c2c2d", fg = "#e6b8e3" })

-- | R language highlights
hi(0, "variable.member.r", { fg = "#5c8473" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#18191f"
g.terminal_color_1 = "#c8aad9"
g.terminal_color_2 = "#aad7a4"
g.terminal_color_3 = "#ccb89c"
g.terminal_color_4 = "#c99297"
g.terminal_color_5 = "#8e9cb4"
g.terminal_color_6 = "#7aacaa"
g.terminal_color_7 = "#b8af9e"
g.terminal_color_8 = "#3c3d43"
g.terminal_color_9 = "#7aacaa"
g.terminal_color_10 = "#aad7a4"
g.terminal_color_11 = "#edb882"
g.terminal_color_12 = "#c99297"
g.terminal_color_13 = "#8e9cb4"
g.terminal_color_14 = "#c8aad9"
g.terminal_color_15 = "#e0d6bd"
