# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter']
quit = ['q']
# movement
list_up = ['k']
list_down = ['j']
page_up = ['ctrl+u']
page_down = ['ctrl+d']
# file panel control
close_file_panel = ['ctrl+x']
create_new_file_panel = ['N']
next_file_panel = [']']
previous_file_panel = ['[']
toggle_file_preview_panel = ['ctrl+p']
open_sort_options_menu = ['alt+s']
toggle_reverse_sort = ['alt+r']
# change focus
focus_on_process_bar = ['ctrl+b']
focus_on_sidebar = ['ctrl+s']
focus_on_metadata = ['ctrl+m']
# create file/directory and rename 
file_panel_item_create = ['n']
file_panel_item_rename = ['r']
# file operate
copy_items = ['y']
paste_items = ['p']
cut_items = ['x']
delete_items = ['d']
# compress and extract
extract_file = ['z']
compress_file = ['Z']
# editor
open_file_with_editor = ['o']
open_current_directory_with_editor = ['O']
# other
pinned_directory = ['.']
toggle_dot_file = ['h']
change_panel_mode = ['m']
open_help_menu = ['?']
open_command_line = [':']
open_spf_prompt = ['>', '']
copy_path = ['ctrl-y']
copy_present_working_directory = ['ctrl+w']
toggle_footer = ['ctrl+f']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter']
cancel_typing = ['esc']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['-']
search_bar = ['/']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cananot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['J']
file_panel_select_mode_items_select_up = ['K']
file_panel_select_all_items = ['A']
